
version: '3.8'
services:
  web:
    container_name: mynginxsite
    image: dimoon023/nginx-apache:latest
    ports:
      - "80:80"
      - "84:84"
      - "83:83"
      - "82:82"
    volumes:
      - ./nginx.html:/usr/share/nginx/html/nginx.html
      - ./page2.html:/usr/share/nginx/html/page2.html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./second.html:/usr/share/nginx/html/second.html
      - ./balance2.html:/usr/share/nginx/html/balance2.html
      - ./balance1.html:/usr/share/nginx/html/balance1.html
  apache:
    container_name: myphpinfo
    image: php:7.2-apache
    ports:
      - "81:81"
    volumes:
      - ./info.php:/var/www/html/info.php
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./ports.conf:/etc/apache2/ports.conf

