version: '3.8'
services:
  web:
    container_name: mynginxsite
    image: ng
    ports:
      - "80:81"
      - "443:443"
      - "83:83"
      - "82:82"
    volumes:
      - ./nginx-apache/nginx.html:/usr/share/nginx/html/nginx.html
      - ./nginx-apache/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-apche/second.html:/usr/share/nginx/html/second.html
  apache:
    container_name: myphpinfo
    image: php:7.2-apache
    ports:
      - "81:80"
    volumes:
      - ./nginx-apache/info.php:/var/www/html/info.php